@startuml

package "Client" {
    [MC Client] --> src
    [Browser] --> https
}

package "Server" {
    package "craftbukkit" {
        dst - [Server]

    }
    package "MCSesame" {
        https - [alibaba]
        [alibaba] --> mqueue
        mqueue - [sesame]
        [sesame] <<privileged>>
        [sesame] --> allow_deny
    }
    package "Linux" {
        [iptables] <<privileged>>
        allow_deny - [iptables]
        dst - [iptables]
        src - [iptables]
    }
}

@enduml